language: python

sudo: false

python: '2.7'

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    openssl aes-256-cbc -K $encrypted_ba1f58cdcb71_key -iv $encrypted_ba1f58cdcb71_iv -in deploy_key.enc -out deploy_key -d ;
    fi

install:
  - pip install mkdocs markdown-checklist
  - pip install https://github.com/mitya57/python-markdown-math/archive/master.zip

script:
  - mkdocs build --clean --verbose
  - bash scripts/deploy.sh
